"""The three references a consumer needs, generated from the code they describe.

The endgame for this project is that another project — the one whose 89 study
diagrams are the reason drawspec exists — can adopt it *without reading the
source*. Three things stood between it and that: what a document may contain,
what the command line takes, and what a theme may set. All three are already
written down inside the code, exactly once, and all three were only readable by
opening a module.

So this is a third rendering of things that already have one, on the same
principle `drawspec.schema` states for the JSON Schema: **one description, many
renderings**. Nothing here is a second source of truth.

* `docs/format.md` — the field tables in `drawspec.schema`, the same ones the
  published JSON Schema is generated from.
* `docs/cli.md` — the argument parser in `drawspec.cli`, walked.
* `docs/theme.md` — the theme dataclasses in `drawspec.theme`, their attribute
  docstrings, and the *effective* defaults, which are the bundled default
  theme's values rather than the dataclasses' own, because every consumer theme
  is merged over that file.

A generated document that is committed can drift from its source, so it is not
allowed to: `tests/test_docs.py` regenerates and compares, and `make docs`
rewrites. This is the arrangement `schema/drawspec-v1.schema.json` already has.

Not shipped code. Usage, from the repository root:

    uv run python tools/docs.py            # write the three references
    uv run python tools/docs.py --check    # report drift, write nothing
"""

from __future__ import annotations

import argparse
import ast
import dataclasses
import inspect
import textwrap
from collections.abc import Iterable, Mapping, Sequence
from pathlib import Path
from typing import Any, Final

from drawspec.cli import OK, REFUSED, USAGE, build_parser
from drawspec.emit import PROFILES
from drawspec.schema import (
    COMMON_FIELDS,
    DOCUMENT_VERSION,
    KIND_PAYLOADS,
    KINDS,
    OBJECTS,
    REJECTED_FIELDS,
    SCHEMA_ID,
    FieldSpec,
)
from drawspec.theme import (
    CYCLE_CONNECTORS,
    EDGE_HEADS,
    FILL_PATTERNS,
    FONT_ROLES,
    NODE_SHAPES,
    THEME_VERSION,
    TYPE_LEVELS,
    WIDTH_MODES,
    BoxStyle,
    Canvas,
    CycleStyle,
    EdgeStyle,
    FitBand,
    FontStacks,
    MarkStyle,
    Padding,
    TitleStyle,
    TypeScale,
    load_theme,
)

ROOT: Final = Path(__file__).resolve().parents[1]
DOCS_DIR: Final = ROOT / "docs"

#: What every generated file says about itself, so nobody edits one by hand.
BANNER: Final = (
    "<!-- Generated by tools/docs.py from the code it describes. "
    "Run `make docs`; do not edit by hand. -->"
)


# ---------------------------------------------------------------------------
# Small markdown helpers
# ---------------------------------------------------------------------------


def _cell(text: str) -> str:
    """One table cell: no newlines, and no pipe that would end the column."""
    return " ".join(text.split()).replace("|", "\\|")


def _table(headings: Sequence[str], rows: Iterable[Sequence[str]]) -> list[str]:
    """A GitHub-flavoured table, or nothing at all when there are no rows."""
    body = [f"| {' | '.join(_cell(value) for value in row)} |" for row in rows]
    if not body:
        return []
    return [
        f"| {' | '.join(headings)} |",
        f"|{'|'.join('---' for _ in headings)}|",
        *body,
    ]


def _block(lines: Sequence[str]) -> list[str]:
    """A section followed by one blank line, or nothing when it is empty."""
    return [*lines, ""] if lines else []


def _code(values: Iterable[str]) -> str:
    return ", ".join(f"`{value}`" for value in values)


def _number(value: float) -> str:
    """Render a float the way a theme file would write it."""
    return str(int(value)) if value == int(value) else str(value)


def _value(value: object) -> str:
    """One theme value, as it appears in TOML — floats keep their point."""
    if isinstance(value, Padding):
        sides = (value.top, value.right, value.bottom, value.left)
        return f"`[{', '.join(repr(side) for side in sides)}]`"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, float):
        return f"`{value!r}`"
    if isinstance(value, tuple):
        return f"`[{', '.join(_quoted(item) for item in value)}]`"
    if isinstance(value, str):
        return f'`"{value}"`'
    return f"`{value}`"


def _quoted(value: object) -> str:
    return f'"{value}"' if isinstance(value, str) else str(value)


# ---------------------------------------------------------------------------
# docs/format.md — the document format, from the field tables
# ---------------------------------------------------------------------------


def _field_type(field: FieldSpec) -> str:
    """A field's type and its constraints, as one phrase.

    Type and constraint are one column on purpose: `array of node, at least 1`
    is the whole answer to "what may I write here", and splitting it across two
    columns makes a reader assemble it.
    """
    if field.enum:
        described = f"string — one of {_code(field.enum)}"
    elif field.kind == "array" and field.item_ref:
        described = f"array of [{field.item_ref}](#{field.item_ref}-object)"
    elif field.kind == "array" and field.item_kind == "point":
        described = "array of `[x, y]` pairs"
    elif field.kind == "array" and field.item_kind:
        described = f"array of {field.item_kind}"
    elif field.kind == "object" and field.ref:
        described = f"[{field.ref} object](#{field.ref}-object)"
    else:
        described = field.kind

    if field.min_items:
        described += f", at least {field.min_items}"
    if field.exclusive_minimum is not None:
        described += f", greater than {_number(field.exclusive_minimum)}"
    return described


def _field_rows(fields: Iterable[FieldSpec]) -> list[list[str]]:
    return [
        [
            f"`{field.name}`",
            _field_type(field),
            "**yes**" if field.required else "no",
            field.description,
        ]
        for field in fields
    ]


def _fields_table(fields: Iterable[FieldSpec]) -> list[str]:
    return _table(("Field", "Type", "Required", "What it is"), _field_rows(fields))


def format_markdown() -> str:
    """`docs/format.md` — every field a document may carry, by kind."""
    lines = [
        BANNER,
        "",
        "# The document format",
        "",
        "A document is JSON. It says what the diagram **means** — the nodes, the",
        "edges, the words, and a semantic role for each — and it carries no",
        "coordinate, no size and no colour, because those are the tool's output",
        "and never its input. The [refused fields](#what-may-not-be-written) at",
        "the end of this page are that rule made mechanical.",
        "",
        f'Every document declares `"version": {DOCUMENT_VERSION}` and one of the',
        f"{len(KINDS)} kinds. The machine-readable form of this page is the published",
        f"JSON Schema, `{SCHEMA_ID}` — point an editor at it with a `$schema` key and",
        "get completion and inline validation for free.",
        "",
        "```json",
        '{ "$schema": "' + SCHEMA_ID + '", "version": 1, "kind": "flow", "nodes": [] }',
        "```",
        "",
        "`drawspec validate doc.json` prints every violation with the JSON pointer of",
        "the place it was written, so one pass over its output is one edit.",
        "",
        "## Every document",
        "",
        "These fields are legal whatever the kind is.",
        "",
        *_fields_table(COMMON_FIELDS),
        "",
        "## What each kind adds",
        "",
        "The `kind` selects a family, and the family selects which further fields are",
        "legal. A field belonging to another family is refused by name rather than",
        "ignored — a `chart` with `nodes` in it is a mistake worth hearing about.",
        "",
    ]

    for kinds, fields in KIND_PAYLOADS.items():
        heading = _code(kinds)
        lines += [f"### {heading}", "", *_fields_table(fields), ""]

    lines += [
        "## The objects",
        "",
        "What the arrays above hold. Every one of them refuses a field it does not",
        "name, so a misspelt key is an error at the point it was written.",
        "",
    ]

    for name, fields in OBJECTS.items():
        lines += [f"### `{name}` object", "", *_fields_table(fields), ""]

    root_legal = {field.name for field in COMMON_FIELDS} & set(REJECTED_FIELDS)
    lines += [
        "## What may not be written",
        "",
        "Every object above refuses a field it does not name. When the field is one of",
        "these, the refusal says *why* rather than just listing the legal keys — and it",
        "carries the JSON pointer of the place it was written. This is the list that",
        "makes the failures in `docs/brief.md` unexpressible rather than merely",
        "discouraged: a document cannot say where a box goes, so a box cannot go in the",
        "wrong place.",
        "",
        "The *Where* column matters. Most of these names are legal nowhere at all. A",
        "few are legal at the **document root** and refused on everything inside it —",
        f"{_code(sorted(root_legal))} size the canvas, which is a budget for the whole",
        "drawing, and are exactly the wrong thing to say about one box in it.",
        "",
        *_table(
            ("Field", "Where it is refused", "Why not"),
            (
                [
                    f"`{name}`",
                    "On any object — legal at the document root"
                    if name in root_legal
                    else "Everywhere",
                    reason,
                ]
                for name, reason in sorted(REJECTED_FIELDS.items())
            ),
        ),
        "",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# docs/cli.md — the command line, from the parser
# ---------------------------------------------------------------------------


def _subcommands(parser: argparse.ArgumentParser) -> dict[str, argparse.ArgumentParser]:
    """The subparsers registered on `parser`, in the order they were added.

    `_SubParsersAction` is argparse's own private name for the action a
    `add_subparsers()` call installs. Reading it is the only way to walk a
    parser's commands, and this is a build-time tool over our own parser, so the
    coupling costs nothing a consumer can feel.
    """
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return dict(action.choices)
    return {}


def _argument_name(action: argparse.Action) -> str:
    if action.option_strings:
        return ", ".join(f"`{option}`" for option in action.option_strings)
    return f"`{action.dest}`"


def _sentence(text: str) -> str:
    """A help string, punctuated, so several of them read as prose side by side."""
    text = text.strip()
    if not text:
        return ""
    text = text[0].upper() + text[1:]
    return text if text.endswith((".", "!", "?")) else text + "."


def _argument_note(action: argparse.Action) -> str:
    """What is written beside an argument: its help, its choices, its default."""
    parts = [_sentence(action.help or "")]
    if action.choices:
        parts.append(f"One of {_code(str(choice) for choice in action.choices)}.")
    # `==SUPPRESS==` is argparse's sentinel for "this flag has no default", worn
    # by --help and --version. Printing it as one is how a reference documents a
    # value that does not exist.
    if (
        action.option_strings
        and action.default not in (None, False)
        and action.default != argparse.SUPPRESS
    ):
        parts.append(f"Default `{action.default}`.")
    return " ".join(part for part in parts if part)


def _arguments_table(command: argparse.ArgumentParser) -> list[str]:
    """Every argument a command takes, minus the two argparse adds itself."""
    rows = [
        [_argument_name(action), _argument_note(action)]
        for action in command._actions
        if not isinstance(action, argparse._HelpAction | argparse._SubParsersAction)
    ]
    return _table(("Argument", "What it does"), rows)


def _command_section(name: str, command: argparse.ArgumentParser) -> list[str]:
    lines = [
        f"### `drawspec {name}`",
        "",
        command.description or "",
        "",
        "```",
        command.format_usage().strip(),
        "```",
        "",
        *_block(_arguments_table(command)),
    ]
    for nested_name, nested in _subcommands(command).items():
        lines += [
            f"#### `drawspec {name} {nested_name}`",
            "",
            nested.description or "",
            "",
            "```",
            nested.format_usage().strip(),
            "```",
            "",
            *_block(_arguments_table(nested)),
        ]
    return lines


def cli_markdown() -> str:
    """`docs/cli.md` — the commands, their arguments, and the exit codes."""
    parser = build_parser()
    lines = [
        BANNER,
        "",
        "# The command line",
        "",
        "```",
        parser.format_usage().strip(),
        "```",
        "",
        "Nothing is printed to stdout but the thing that was asked for — the SVG, the",
        "schema, or a one-line confirmation — so `drawspec render doc.json > doc.svg`",
        "is safe. Refusals go to stderr **in full**: the message names the remedy as",
        "well as the fault, and a build script that truncates it to a summary line is a",
        "build script whose author ends up guessing.",
        "",
        "## Exit codes",
        "",
        "The split is worth stating: **2 is about the invocation, 1 is about the",
        "content.** A misspelt flag or an unknown profile is 2 — nothing was read, so",
        "nothing can be said about it. A document that cannot be read, cannot be parsed,",
        "or cannot be fitted is 1, and a refusal is an outcome, not a crash.",
        "",
        *_table(
            ("Code", "Meaning"),
            [
                [f"`{OK}`", "It worked."],
                [f"`{REFUSED}`", "The document, the theme or the fit was refused."],
                [f"`{USAGE}`", "The command line itself was wrong."],
            ],
        ),
        "",
        "## Global options",
        "",
        "Legal before the command name.",
        "",
        *_block(_arguments_table(parser)),
        "## Commands",
        "",
    ]
    for name, command in _subcommands(parser).items():
        lines += _command_section(name, command)

    lines += [
        "## Embedding profiles",
        "",
        f"`render --profile` takes {_code(PROFILES)}.",
        "",
        "* **`inline`** — for pasting into a Markdown or HTML page. Strokes are",
        "  `currentColor`, so the drawing inherits the page's ink and follows it into",
        "  dark mode; there is no `<style>` block to leak, and every id is scoped so two",
        "  diagrams on one page cannot collide.",
        "* **`standalone`** — for a linked `.svg`, a PDF conversion, or anywhere there",
        "  is nothing to inherit from. `currentColor` is resolved to the theme's",
        "  `[canvas] ink`, because a converter's own default is not a design decision.",
        "",
        "## Themes",
        "",
        "`--theme` takes a bundled theme name or the path of a TOML file. See",
        "[the theme reference](theme.md) for every key a theme may set, and",
        "[the guide](guide.md) for how to write one.",
        "",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# docs/theme.md — the theme keys, from the dataclasses
# ---------------------------------------------------------------------------

#: `[section]` in a theme file → the dataclass that reads it. Ordered as a
#: theme file reads: the canvas, then the type, then the things drawn on it.
THEME_SECTIONS: Final[Mapping[str, type]] = {
    "canvas": Canvas,
    "font": FontStacks,
    "scale": TypeScale,
    "fit": FitBand,
    "box": BoxStyle,
    "edge": EdgeStyle,
    "mark": MarkStyle,
    "title": TitleStyle,
    "cycle": CycleStyle,
}

#: Closed vocabularies, by the key that is checked against them. The values are
#: the constants themselves, so a vocabulary that gains a member cannot leave
#: this page stale — only a *new* constrained key needs adding here.
THEME_VOCABULARIES: Final[Mapping[tuple[str, str], tuple[str, ...]]] = {
    ("canvas", "width_mode"): WIDTH_MODES,
    ("font", "default"): FONT_ROLES,
    ("mark", "fills"): FILL_PATTERNS,
    ("title", "level"): TYPE_LEVELS,
    ("cycle", "connector"): CYCLE_CONNECTORS,
}


def attribute_docs(cls: type) -> dict[str, str]:
    """Each field's own docstring — the string literal written under it.

    Python discards these at runtime, which is why they are read back out of the
    source. They are where the *reason* for a value lives, and the reason is the
    part a theme author needs; the first paragraph is the summary and the rest is
    the argument, so only the first paragraph comes here.
    """
    tree = ast.parse(textwrap.dedent(inspect.getsource(cls)))
    definition = tree.body[0]
    if not isinstance(definition, ast.ClassDef):  # pragma: no cover — always a class
        return {}

    docs: dict[str, str] = {}
    previous: str | None = None
    for statement in definition.body:
        if isinstance(statement, ast.AnnAssign) and isinstance(statement.target, ast.Name):
            previous = statement.target.id
            continue
        literal = (
            statement.value
            if isinstance(statement, ast.Expr) and isinstance(statement.value, ast.Constant)
            else None
        )
        if previous and literal is not None and isinstance(literal.value, str):
            docs[previous] = textwrap.dedent(literal.value).strip().split("\n\n")[0]
        previous = None
    return docs


def _section_rows(section: str, cls: type, values: Any) -> list[list[str]]:
    docs = attribute_docs(cls)
    rows = []
    for field in dataclasses.fields(cls):
        value = getattr(values, field.name)
        vocabulary = THEME_VOCABULARIES.get((section, field.name))
        described = docs.get(field.name, "")
        if vocabulary:
            each = "Each one of" if isinstance(value, tuple) else "One of"
            described = f"{described} {each} {_code(vocabulary)}.".strip()
        rows.append([f"`{field.name}`", _value(value), described])
    return rows


def _role_rows(roles: Mapping[str, Any]) -> list[list[str]]:
    return [
        [f"`{name}`"] + [_value(getattr(role, field.name)) for field in dataclasses.fields(role)]
        for name, role in roles.items()
    ]


def theme_markdown() -> str:
    """`docs/theme.md` — every key a theme may set, and what the default sets it to."""
    default = load_theme(None)
    lines = [
        BANNER,
        "",
        "# The theme reference",
        "",
        "A theme is **data, not code**: a TOML file a consumer versions and diffs",
        "without importing drawspec. It owns every appearance decision — type size,",
        "stroke weight, shape per role, the canvas width — so that no document has to,",
        "and so that changing one changes every diagram at once.",
        "",
        f"Every theme declares `version = {THEME_VERSION}`, and that is the one key not",
        "inherited: a file must state which format it was written against, or a future",
        "v2 would load as a v1. Everything else is **merged over the bundled default**,",
        "leaf by leaf, so a theme declares only what it changes. The values in the",
        "*Default* columns below are therefore what a key holds if a theme is silent",
        "about it — they are read from the bundled `default.toml`, not from the code's",
        "own fallbacks.",
        "",
        "```toml",
        "version = 1",
        'name = "house"',
        "",
        "[scale]",
        "body = 12.0        # everything else keeps the default",
        "```",
        "",
        "`drawspec theme check house.toml` loads it and runs its invariants.",
        "[The guide](guide.md#writing-a-theme) walks through writing one.",
        "",
        "## The greyscale invariant",
        "",
        "Two roles may not be distinguishable **by colour alone**. The loader compares",
        "every pair and refuses the theme if a pair differs in no other channel, which",
        "is why the tables below carry `shape`, `dash`, `fill_pattern` and",
        "`stroke_width` beside `stroke`: those are what has to do the work. A diagram",
        "that loses its meaning in a black-and-white printout is a diagram that lost it",
        "in dark mode too, and neither is caught by looking at the screen it was made",
        "on.",
        "",
        "Colour is not forbidden — the bundled `accent` theme uses it. It may *point*,",
        "and it may never *carry*.",
        "",
        "## Sections",
        "",
    ]

    for section, cls in THEME_SECTIONS.items():
        summary = (inspect.getdoc(cls) or "").split("\n\n")[0]
        lines += [
            f"### `[{section}]`",
            "",
            summary,
            "",
            *_table(
                ("Key", "Default", "What it is"),
                _section_rows(section, cls, getattr(default, section)),
            ),
            "",
        ]

    lines += [
        "## `[role.*]` — the node roles",
        "",
        "A document names a role; the theme decides what that role looks like. The",
        f"vocabulary is closed: {_code(default.roles)}. `shape` is one of",
        f"{_code(NODE_SHAPES)} and `fill_pattern` one of {_code(FILL_PATTERNS)}.",
        "",
        *_table(
            (
                "Role",
                *(
                    f"`{field.name}`"
                    for field in dataclasses.fields(next(iter(default.roles.values())))
                ),
            ),
            _role_rows(default.roles),
        ),
        "",
        "## `[edge_role.*]` — the edge roles",
        "",
        "The same arrangement for connectors, and it is where a connector that is *not*",
        "an arrow lives: an author says two things are merely associated (`link`) and",
        "the theme decides that means a line with no head. `head` and `tail` are each",
        f"one of {_code(EDGE_HEADS)}.",
        "",
        *_table(
            (
                "Role",
                *(
                    f"`{field.name}`"
                    for field in dataclasses.fields(next(iter(default.edge_roles.values())))
                ),
            ),
            _role_rows(default.edge_roles),
        ),
        "",
        "## The bundled themes",
        "",
        *_table(
            ("Theme", "What it is for"),
            [
                [
                    "`default`",
                    "Ink only. Every stroke is `currentColor`, so a diagram follows its page.",
                ],
                [
                    "`accent`",
                    "Colour that points and never carries: six roles are coloured, and every one "
                    "of them already differed from its neighbours by weight, dash or shape.",
                ],
                [
                    "`wheel`",
                    'The broad tapered cycle connector — `[cycle] connector = "band"` — for a '
                    "cycle drawn loudly.",
                ],
            ],
        ),
        "",
    ]
    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Writing them out
# ---------------------------------------------------------------------------

#: Path → the function that generates it.
GENERATED: Final[Mapping[str, Any]] = {
    "format.md": format_markdown,
    "cli.md": cli_markdown,
    "theme.md": theme_markdown,
}


def generate() -> dict[Path, str]:
    """Every generated reference, as path → intended content."""
    return {DOCS_DIR / name: build() for name, build in GENERATED.items()}


def stale(documents: Mapping[Path, str] | None = None) -> list[Path]:
    """The generated documents whose committed content is not what we would write."""
    documents = documents if documents is not None else generate()
    return [
        path
        for path, content in documents.items()
        if not path.is_file() or path.read_text(encoding="utf-8") != content
    ]


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="report drift, write nothing")
    arguments = parser.parse_args(argv)

    documents = generate()
    outdated = stale(documents)
    if arguments.check:
        for path in outdated:
            print(f"stale: {path.relative_to(ROOT)} — run `make docs`")
        return 1 if outdated else 0

    for path, content in documents.items():
        path.write_text(content, encoding="utf-8")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
